In [5]:
import code.utils.graph
import graph_tool.all as gt
import os
import ast
import re

print(os.getcwd())

def build_input_format(inputs_str):
    res = re.search('\[(.*)\]', inputs_str)
    return dict.fromkeys(res.group(1).split(','), 0) if res else {}
    

def build_graph_skeleton(g_str):
    g_elements = g_str.split('\n')
    g_name = g_elements[0].split(',')[1:]
    g_id = 0
    g_queuetime = 0
    
    g = gt.Graph(directed=True)
    g.gp['name'] = g.new_graph_property("string", g_name)
    g.gp['id'] = g.new_graph_property("string", str(g_id))
    g.gp['queue_time'] = g.new_graph_property("int", g_queuetime)
    g.gp['cur_stage'] = g.new_graph_property("int", -1)
    status = g.new_vertex_property("int")
    inputs = g.new_vertex_property("object")
    cache_runtime = g.new_vertex_property("int")
    remote_runtime = g.new_vertex_property("int")
    ops = g.new_vertex_property("vector<string>")

    # build vertices
    for el in g_elements[1:]:
        if el.startswith('v'):
            vid, inputs_str, operation = el.split(',')[1:]
            v = g.add_vertex()
            
            inputs[v] = build_input_format(inputs_str)
            cache_runtime[v] = 0
            remote_runtime[v] = 0 
            ops[v] = operation.split('|')
    
    # build edges
    for el in g_elements[1:]:
        if el.startswith('e'):
            v_src, v_dest = el.split(',')[1:]
            e = g.add_edge(v_src, v_dest)
    return g
            

def load_graph_skeleton(path):
    graph_skeletons = {}
    with open(path, 'r') as fd:
        graph_strs = fd.read().split('#')[1:]

        for g_str in graph_strs:
            g= build_graph_skeleton(g_str)
            graph_skeletons[g.gp.name] = g
    return graph_skeletons
            
path = "../tpch_pig_dags.g"
graph_skeletons = load_graph_skeleton(path)

print(graph_skeletons)

/local0/Kariz/expriments/macrobenchmark/ipython
{"['Q1']": <Graph object, directed, with 4 vertices and 3 edges at 0x7f92b1b8c748>, "['Q2']": <Graph object, directed, with 8 vertices and 7 edges at 0x7f92b1b8c6d8>}

In [6]:
import code.utils.graph
import graph_tool.all as gt
import os
import ast
import re

import workload.sequential as sqw
import sys

print(os.getcwd())

config_file = "../config.json"

workload = sqw.Sequential(config_file)

print(workload.graph_skeleton_pool)

/local0/Kariz/expriments/macrobenchmark/ipython
{
  "type": "sequential",
  "graph_src": "file",
  "graph_skeleton_path": "/local0/Kariz/expriments/macrobenchmark/tpch_pig_dags.g",
  "stat_file_path": "/local0/Kariz/expriments/macrobenchmark/pig_tpch_stats",
  "input_dir": "s3a://data/pig-tpch/64G",
  "output_dir": "/tpch-64G-output",
  "benchmark_path": "/local0/Kariz/expriments/benchmark/BenchmarkScripts/tpch/pig"
}
{'Q1': <Graph object, directed, with 4 vertices and 3 edges at 0x7fd17eacd550>, 'Q2': <Graph object, directed, with 8 vertices and 7 edges at 0x7fd17eacd4e0>, 'Q3': <Graph object, directed, with 6 vertices and 5 edges at 0x7fd17eacd4a8>}

In [8]:
# Load statistics
import utils.jobhistory as hist
import pandas as pd

print(workload.configs['stat_file_path'])

jobs_stats = pd.read_csv(workload.configs['stat_file_path'])

jobs_stats[jobs_stats].apply(process_tasks, axis=1)

#jobs = jobs.apply(process_tasks, axis=1)

/local0/Kariz/expriments/macrobenchmark/pig_tpch_stats

,query,dataset_size,node_id,jobid,type,runtime,maptime
0,Q1,64,0,job_1590090272562_0037,remote,0,NaN
1,Q1,64,1,job_1590090272562_0038,remote,0,NaN
2,Q1,64,2,job_1590090272562_0039,remote,0,NaN
3,Q1,64,0,job_1590090272562_0040,cache,0,NaN
4,Q1,64,1,job_1590090272562_0041,cache,0,NaN
5,Q1,64,2,job_1590090272562_0042,cache,0,NaN
6,Q2,64,0,job_1590090272562_0043,remote,0,NaN
7,Q2,64,1,job_1590090272562_0044,remote,0,NaN
8,Q2,64,2,job_1590090272562_0045,remote,0,NaN
9,Q2,64,3,job_1590090272562_0046,remote,0,NaN
10,Q2,64,4,job_1590090272562_0047,remote,0,NaN
11,Q2,64,5,job_1590090272562_0048,remote,0,NaN
12,Q2,64,6,job_1590090272562_0049,remote,0,NaN
13,Q2,64,7,job_1590090272562_0050,remote,0,NaN
14,Q2,64,0,job_1590090272562_0054,cache,0,NaN
15,Q2,64,1,job_1590090272562_0055,cache,0,NaN
16,Q2,64,2,job_1590090272562_0056,cache,0,NaN
17,Q2,64,3,job_1590090272562_0057,cache,0,NaN
18,Q2,64,4,job_1590090272562_0058,cache,0,NaN
19,Q2,64,5,job_1590090272562_0059,cache,0,NaN
20,Q2,64,6,job_1590090272562_0060,cache,0,NaN
21,Q2,64,7,job_1590090272562_0061,cache,0,NaN
22,Q2,64,0,job_1590090272562_0061,cache,0,NaN
23,Q2,64,1,job_1590090272562_0062,cache,0,NaN
24,Q2,64,2,job_1590090272562_0063,cache,0,NaN
25,Q2,64,3,job_1590090272562_0064,cache,0,NaN
26,Q2,64,4,job_1590090272562_0065,cache,0,NaN
27,Q2,64,5,job_1590090272562_0066,cache,0,NaN
28,Q2,64,0,job_1590090272562_0067,cache,0,NaN
29,Q2,64,1,job_1590090272562_0068,cache,0,NaN
30,Q2,64,2,job_1590090272562_0069,cache,0,NaN
31,Q2,64,3,job_1590090272562_0070,cache,0,NaN
32,Q2,64,4,job_1590090272562_0071,cache,0,NaN
33,Q2,64,5,job_1590090272562_0072,cache,0,NaN